# Use postgres/example user/password credentials
version: '3.7'

services:

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=ntetikova
      - POSTGRES_PASSWORD=12345
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
